### ISSUE TITLE
Grammar doesn't support punctuation symbols and other testing

### ISSUE THREAD

**Issue by schan219** [schan219/lang#5]
Currently, the grammar doesn't support punctuation symbols like +, -, !, etc., and we should add that to our grammar as well as unit tests. Also, we need to write a test for multiple definitions.

It turns out that our tokenizer cannot read symbols like + without customizing the lexer.

**Comment by shade** [comment]
Does this mean we can't do `(+ 1 2)` ?

**Comment by schan219** [comment]
Yes, the + symbol doesn't fit anywhere into our AST when we expected it to fit into Atom, which is an @Ident. I believe the default tokens that match with @Ident are alphanumerics and underscore (from the GraphQL EBNF in the library README, though I don't know if the lexer using that exact one by default). We may need a new entry for punctuation (@Punct).

**Comment by schan219** [comment]
It turns out by default, the lexer uses the Go package "text/scanner" and not EBNF. That means our Ident, String and Int should be identical to Golang identifiers, strings and ints.

**Comment by schan219** [comment]
```
Manually Built AST
&parser.Program{
  Definitions: []*parser.DefOrMain{
    &parser.DefOrMain{
      Main: &parser.Main{
        Body: &parser.Expr{
          Atom: "+",
        },
      },
    },
  },
}
Participle Build AST with default lexer
&parser.Program{
  Definitions: []*parser.DefOrMain{
    &parser.DefOrMain{
      Main: &parser.Main{
      },
    },
  },
}
Participle Built AST with custom EBNF
&parser.Program{
}
&{[]}
--- FAIL: TestSymbol (0.00s)
panic: runtime error: index out of range [recovered]
        panic: runtime error: index out of range

goroutine 24 [running]:
testing.tRunner.func1(0xc0420fe780)
        C:/dev/Go/src/testing/testing.go:711 +0x2d9
panic(0x6ad660, 0x87b870)
        C:/dev/Go/src/runtime/panic.go:491 +0x291
lang/test/parser.TestSymbol(0xc0420fe780)
        C:/Go/src/lang/test/parser/lexer_test.go:67 +0x878
testing.tRunner(0xc0420fe780, 0x7184c0)
        C:/dev/Go/src/testing/testing.go:746 +0xd7
created by testing.(*T).Run
        C:/dev/Go/src/testing/testing.go:789 +0x2e5
FAIL    lang/test/parser        0.131s
make: *** [all] Error 1
```

The first AST is manually built and therefore has everything. The second AST is built by participle using the default lexer "text/scanner". It doesn't seem to recognize the "+" symbol. The third AST is built by participle using a custom EBNF that I put together. It compiles, but parses nothing and fails silently. The tests fail and induce panic because the custom EBNF AST is the one I am testing on and it is not working. I think we want to make the custom EBNF option work because we need symbols like "+". Everything that generates the output above is currently pushed onto the branch corresponding with this issue. I am trying to figure out what is wrong with the EBNF and/or grammar. If you have any ideas, do let me know.

**Comment by shade** [comment]
Oh okay gotcha, 

According to the [golang spec,](https://golang.org/ref/spec#Id) all Identifiers are defined just like you inferred earlier from the  GraphQL thing i.e. underscores and alphanumeric.

Looking at the text/scanner package, it seems as though Scanner has a modifiable predicate function `IsIdentRune`. You could probably modify that to include the `+` and `-` symbol just like the [example](https://golang.org/pkg/text/scanner/#example__isIdentRune) given at the end of the page.

```go

// treat leading '%' as part of an identifier
s.IsIdentRune = func(ch rune, i int) bool {
	return ch == '%' && i == 0 || unicode.IsLetter(ch) || unicode.IsDigit(ch) && i > 0
}
```

Only issue is that we just have to fork the participle package.
